### PR TITLE
Updated sponsor page

### PR DESCRIPTION
**Pull request by afreemantle**

### CODE REVIEW

**Comment by leee** [comment]
-1, you're missing the team subnav.

**Comment by afreemantle** [comment]
The team subnav shows up fine when I launch the site. I only updated sponsors.md and added sponsor logos to the assets folder. Where do you see the subnav missing?

**Comment by kevin1** [comment]
@leee  sounds like you're gonna review this one?

**Comment by leee** [comment]
@kevin1 yeah, but if you want to, I'd be glad to defer to you.

Hrm, weird, I was hitting a race condition or something, I see the team subnav now. Seeing as this was pretty much a "look at current code and copy" job, everything appears sane, so +2.

**Comment by afreemantle** [comment]
Great, can I merge?

**Comment by leee** [comment]
Yes @AFreemantle

**Comment by leee** [comment]
@AFreemantle you can handle deploy?

**Comment by afreemantle** [comment]
Kevin usually does it. I should know how we deploy though. Do we have an event listener in place?

**Comment by leee** [comment]
I'm pretty sure it's a manual task, there's no hook involved.

**Comment by afreemantle** [comment]
Oh okay, we are going to have to ask @kevin1

**Comment by leee** [comment]
@AFreemantle check https://beta.columbiafsae.org - okay, evidently, it's my own installation that's not providing the header class `subheader`. Does this not happen for you?

**Comment by leee** [comment]
Okay, I forgot jekyll is absurd about if statements - I was using jekyll 3.1.2. I'm not going to waste time exploring why jekyll thinks backwards compatibility should go out the window. Rebuilding and deploying with 2.4.

**Comment by leee** [comment]
@AFreemantle check https://beta.columbiafsae.org/.

For future notice, I think we should settle on a specific version of jekyll until this can be dealt with. @kevin1 and Alex, what versions of jekyll do you all use?

**Comment by kevin1** [comment]
jekyll 2.5.3 on my machine

**Comment by leee** [comment]
alright, just so we don't have this headache for the near future, I'm going to specify that version in the Gemfile. Thanks @kevin1

**Comment by leee** [comment]
Done so in 06f1537. As I mention, someone will have to deal with this in the future, but it's a small enough debt we can do this and deal with it later.

**Comment by afreemantle** [comment]
Sorry Eugene, I was away from my computer. https://beta.columbiafsae.org/ looks fine for me. 
jekyll 3.0.0 on my machine.

**Pull request merged**
