### PR TITLE
Team 2016

### PR DESCRIPTION
**Pull request by afreemantle**
I removed people who were no longer members and added people who were missing to the team page. For those who didn't have a photo, I just put an FSAE logo watermarked in its place.

### CODE REVIEW

**Comment by afreemantle** [comment]
Hmm.. why are there conflicts this time?

**Comment by kevin1** [comment]
looks good, just one thing:
- let's move fsae_logo_light to the parent directory, since it's not tied to people graduating in a specific year (i.e. `assets/team/members/fsae_logo_light.jpg`)

it's because this was done on the team_2016 branch, not created off master. Here's how to fix:
1. Ensure you have the latest master: `git checkout master && git pull origin master`
2. Copy the most recent commit from team_2016: `git cherry-pick team_2016`
3. `git push origin master`

**Comment by afreemantle** [comment]
I moved the logo and adjusted the path in team.2016.md on the team_2016 branch and then committed those changes. I then followed the steps you listed above. When I go to submit another pull request git tells me the changes cannot be automatically merged. How can I check that the cherry-pick worked? Should my latest commit on the team_2016 branch show up when I run "git log" on master?

**Comment by kevin1** [comment]
> Should my latest commit on the team_2016 branch show up when I run "git log" on master?

Yes

Also note that cherry-pick only takes the most recent commit. Since you now have 3 commits, i would try squashing them first. Make sure you only squash the 3 new ones or there will be more conflicts.

**Comment by afreemantle** [comment]
Ahhh okay, I will give that a try.

**Comment by afreemantle** [comment]
I squashed my commits but when I switched to the master branch and pulled, auto merging on team.2016.md failed. Cherry-pick also failed but "git log" is showing my most recent commit from the team_2016 branch. How do I resolve the merge conflict on team.2016.md?

**Comment by kevin1** [comment]
let's delete your local master branch and replace it with origin/master:
1. get the latest branches from origin `git fetch`
2. switch to master `git checkout master`
3. `git reset --hard origin/master`

Now to cherry-pick again and see what happens

**Comment by afreemantle** [comment]
Upon running "git checkout master" I get these messages:
"team/team.2016.md: needs merge
error: you need to resolve your current index first"

**Comment by kevin1** [comment]
sounds like git is still in the middle of a merge. you need to get rid of the merge first http://stackoverflow.com/a/2534968/1489823

**Comment by afreemantle** [comment]
Everything looks good now. Thanks for your help Kevin!

**Comment by kevin1** [comment]
looks like you already merged. deployed.

**Pull request closed without merging**
