### PR TITLE
Updated the Gallery

### PR DESCRIPTION
**Pull request by pr**
The gallery is completely done.

### CODE REVIEW

**Comment by kevin1** [comment]
- Please use the standard subnav (see the cars or team pages)
  screen shot 2016-01-12 at 10 36 22 am
- Also all the links on that page are broken
- Do not commit thumbnail files to the tree. They are generated automatically by the thumbnailer plugin when you compile the site.
- The [2008-2015].html files in gallery should not have the html head copy and pasted. They should be generated through the templating system. Please see basically any other page on the site for an example.

**Comment by pr** [comment]
Hi Kevin! Thanks for the feedback, I really appreciate it. Could you tell me what browser you were using? All the links were working great on Chrome and Edge.

**Comment by kevin1** [comment]
It's not a matter of browser - it's that your web server happens to accept `/2014/` as a valid path for `/2014.html`. Relying on implementation-specific behavior isn't a good idea so you should make sure all URLs match the actual file. 

In this case, I would recommend putting them in /2014/index.html. You can use the permalink property in the jekyll front matter to accomplish this without making a bunch of directories.

**Comment by pr** [comment]
I fixed the links, thanks for the heads up. I had no idea about the implementation-specific behavior, always good to learn something new. 

Regarding the standard subnav, I think the buttons work better in this instance. In a text dominated section of the website, such as the Team one, the standard subnav makes sense, but in the more visual Gallery I preferred the buttons. They also look great on mobile, which I think is important too. 

Regarding the thumbnail plugin, it wasn't working for me so I just went ahead and made thumbnails. I was only 1 additional click. Next time I'll give thumbnailer plugin another shot, but for now I think the thumbnails will work just fine for the initial implementation. 

I don't plan on using the the templateing system for each year, as after you deploy the initial update I plan on customizing each page a little more with additional information. I believe this customization will mean 1 template for each page will not suffice.

For now, everything is fully functional and looks great. Let me know if you need anything else before deploying, and I'll get started on that next update. Thanks again!

**Comment by pr** [comment]
What's the holdup Kevin?

**Comment by pr** [comment]
Hey Kevin, hope the start of the semester is treating you well. Could you deploy this soon please? Thanks!

**Comment by kevin1** [comment]
Peter, I have already covered above why we can't merge this. It is important to use the templates system otherwise you will end up with an unmaintainable site. 

I was just looking at the diff again and the gallery pages don't have Google analytics. This is another error that could be prevented with using templating.

**Comment by pr** [comment]
Thanks for the heads up! I'm not sure that lack of Google analytics is enough reason to not deploy. I'm happy to add that in the coming weeks, but for now I think it would be great if we could get a bigger gallery up as soon as possible. This is already delayed, and I know some members were hoping to see this sooner rather than later. 

I'm a little unclear on the unmaintainable site point. As I wrote before, I think the level of customization I would like to implement for each year precludes a template. Could you maybe elaborate? Thank you so much, you've taught me quite a lot about web development.

**Comment by kevin1** [comment]
Templating ensures that your boilerplate code -- such as html head, base css, buttons, bars, etc don't have to be reimplemented on each page. Let's say I want to change from google analytics to adobe omniture. On an N-page website, without templating I'd have to run around to every page, making N edits. With templating, I only have to make 1 change, and jekyll does the heavy lifting when the site is compiled.

**Comment by pr** [comment]
That makes a lot of sense, I didn't consider that you would want to make that sort of change. Let me head back to the drawing board, I'll make a new pull request that takes into account these ideas. Thanks so much, this has been incredibly informative!

**Pull request closed without merging**
