### PR TITLE
Gallery 2.0

### PR DESCRIPTION
**Pull request by pr**
I have completely finished the gallery.

### CODE REVIEW

**Comment by pr** [comment]
@kevin1 How does this look?

**Comment by leee** [comment]
@AFreemantle you should CR this, since I did #12. I believe @kevin1 is a bit predisposed at the moment due to TA work.

**Comment by afreemantle** [comment]
@leee fair enough.

**Comment by leee** [comment]
@AFreemantle the gallery looks good, and it looks like it's mergable. Here's my :+1:, but I want you to give the final say.

In particular, the images themselves could use some work - they're pretty huge and unwieldy. If you're too hosed, you could potentially get @mattsher15 to do it for you.

**Comment by mattsher15** [comment]
@prichardsf if I remember correctly, the navigation for the gallery was at the side of the page, for consistency in the website, it should be at the top. See the team pages. @AFreemantle please push Richard's current one to the website when you have a chance, but we'll have to go back and tweak it.

**Comment by leee** [comment]
@AFreemantle needs to code review first.

**Comment by pr** [comment]
@mattsher15 I think this particular update does use the standard website subheader. The previous one did not, which is why I went back to the drawing board. See Pull Request #10

**Comment by afreemantle** [comment]
Hey @prichardsf, everything is looking good but most of the new pictures do not render when I launch the site. @leee, did you notice this when you launched the site? The photos missing have the uppercase ".JPG" extension rather than the lowercase ".jpg". You need to rename the uppercase files.

**Comment by pr** [comment]
Good catch! Thanks for letting me know! I had that issue when I made the new site, I renamed them already. Should be a simple fix, give me a sec

**Comment by pr** [comment]
Didn't work. Do you have any ideas how to bring the pictures over with their new lower case names from here? @AFreemantle https://github.com/knickerbockermotorsports/knickerbockermotorsports.github.io/tree/master/assets/images/full

**Comment by afreemantle** [comment]
It might be easier to use the "rename" command. Take a look here: http://tips.webdesign10.com/how-to-bulk-rename-files-in-linux-in-the-terminal

**Comment by leee** [comment]
My filesystem is case-insensitive so I did not experience this issue. You're right, this should be fixed before throwing into staging then to production.

**Comment by pr** [comment]
Should be fixed! Thank you for the feedback @AFreemantle 
Let me know if there's any other issues

**Comment by afreemantle** [comment]
Looks good.

**Comment by leee** [comment]
This website just became extremely heavy - this should be dealt with. In any case, this has been deployed to https://beta.columbiafsae.org.

@columbiafsae/developers , one of you should look over it - _very carefully_. If it all looks good, put it into production (or let me know and I'll do it).

**Comment by pr** [comment]
Before 2008 doesn't look like it is working either, I'll take a look after midterms

**Comment by tmo2116** [comment]
+1, gallery is definitely an improvement, nothing looks broken. What needs to happen next to push this to production? @leee can you take care of this?

**Comment by leee** [comment]
@columbiafsae/developers deployed to production.

**Comment by tmo2116** [comment]
Sorry that I didn't notice this earlier. Under the sponsors page under radium engineering "fuel" is misspelled as "feul".

**Comment by tmo2116** [comment]
Just did a spell check, there are a bunch of typos: 

Under "Columbia university mechanical engineering": Friendliest is spelled as friendlist
Under "Monster Tool": Specialty is spelled as "speciality"
Under "Atlassian": There is no space between more.Confluence
Under "Hexion": Fiber is spelled "fibre"
Under "Radium engineering LLC": Fuel is spelled "feul"
Under "Steinjager":  Components is spelled "componenets"; Suspensions is spelled "suspesions"

Under Cars / 2014: Innovation is spelled "invoation"

**Comment by pr** [comment]
@tmo2116 These issues aren't relevant to the gallery. Maybe create an issue? I'm not sure what the proper work flow is, but I don't think this is it

**Comment by mattsher15** [comment]
yeab tom, go to "IT" and find the update sponsors task that is assigned to
alex

**Comment by afreemantle** [comment]
Hey guys, spelling errors are my bad. I totally forgot to do a spell check before I pushed my changes. I will reopen my last pull request, fix the spelling errors and push again.

**Pull request merged**
